name: mi_app_android
description: "Aplicación de control de gastos personales"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  intl: ^0.19.0  # Versión actualizada para compatibilidad
  shared_preferences: ^2.2.2
  date_format: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite: ^2.3.0
  path_provider: ^2.1.2

flutter:
  uses-material-design: true